"""Add factual_inaccuracies and weighted_breakdown to question_attempts

Revision ID: 003
Revises: 002
Create Date: 2026-07-11
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempts', sa.Column('factual_inaccuracies', sa.JSON(), nullable=True))
    op.add_column('question_attempts', sa.Column('weighted_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_attempts', 'weighted_breakdown')
    op.drop_column('question_attempts', 'factual_inaccuracies')
    # ### end Alembic commands ###
